### ISSUE TITLE
Make ipython work with all themes

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#1782]
AFAIK this involves:

- [x] Adding some CSS (the CSS needs reviewing)
- [x] Enabling mathjax for ipynb posts/stories

Is there anything else, @damianavila ?

**Comment by damianavila** [comment]
I don't think so... should be enough... btw, the ipython/jupyter css does not have to break the themes for people not using ipynbs...

**Comment by Kwpolska** [comment]
We could check if the user has any posts that would be compiled with ipynb, and if yes, include the CSS.

**Comment by ralsina** [comment]
And mark those posts as mathjax immediately.

**Comment by damianavila** [comment]
yes... sounds like a good idea...

**Comment by Kwpolska** [comment]
We need some changes to the CSS.  This should be deleted:

```css
body {
  position: static;
}

pre {
  padding: 0.4em;
  margin: 0px;
  font-family: monospace, sans-serif;
  border: none;
}
```

We should also look into the highlight things.
