### ISSUE TITLE
Code block does not indent well

### ISSUE THREAD

**Issue by matclab** [getnikola/nikola#2939]
### Environment (if reporting a bug)

**Python Version:** Python 3.6.4

**Nikola Version:** 7.8.10

**Operating System:** Arch linux

### Description: 

An indeted code block isn't translated as expected. For example, in the following, the indented code-block : 

```
1. Créer un projet sur la `console google cloud 
   <https://console.cloud.google.com/project>`__
2. Mettre le fichier `app.yaml` suivant dans le répertoire `files` à la racine 
   du projet :

   .. code-block::

      runtime: python27
      api_version: 1
      threadsafe: true

      handlers:
      - url: /
        static_files: index.html
        upload: index.html

      - url: /(.*)
        static_files: \1
        upload: (.*)
```
is translated as as (note the space before second and following lines wich break the source code alignment):
```
…
  <pre class="code text"><a name="rest_code_5144ab119866433cbcf624774a14dbe7-1"></a>run­ti­me: py­thon27
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-2"></a>api_­ver­sion: 1
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-3"></a>thread­sa­fe: true
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-4"></a> 
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-5"></a>hand­lers:
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-6"></a>- url: /
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-7"></a>   sta­tic_­fi­les: in­dex.html
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-8"></a>   upload: in­dex.html
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-9"></a> 
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-10"></a>- url: /(.*)
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-11"></a>   sta­tic_­fi­les: \1
 <a name="rest_code_5144ab119866433cbcf624774a14dbe7-12"></a>   upload: (.*)
 </pre>

```

Note that `rst2hlm` translates as expected.

For information, I use:
```
HYPHENATE = True
FILTERS = {
   ".html": [filters.typogrify],
}
```
