### ISSUE TITLE
Decide whether reSt files use .rst or .txt and stick to it

### ISSUE THREAD

**Issue by ralsina** [getnikola/nikola#2981]
Currently we use both inconsistently in the demo site.

That has asucky side effect in that the effective minimal config is this:

```yaml
POSTS:
  - [posts/*.rst, "", post.tmpl]
PAGES:
  - [pages/*.rst, "", page.tmpl]
  - [pages/*.txt, "", page.tmpl]
```

which is kinda silly.
