### ISSUE TITLE
un-captioned images in metadata.yml

### ISSUE THREAD

**Issue by jmcp** [getnikola/nikola#3076]
### Environment (if reporting a bug)

**Python Version:** 3.5

**Nikola Version:** 8.0.0b1

**Operating System:**  Solaris 11.4

### Description:

 I have a test metadata.yml which does not have captions for all images in a specific gallery. I noticed with the 8.0.0b1 build that the images without captions have "None" printed for the caption when viewing the gallery.

**Comment by jmcp** [comment]
I hacked up this fix:

```
$ git diff
diff --git a/nikola/plugins/task/galleries.py b/nikola/plugins/task/galleries.py
index dd969d26..6b34313f 100644
--- a/nikola/plugins/task/galleries.py
+++ b/nikola/plugins/task/galleries.py
@@ -465,6 +465,8 @@ class Galleries(Task, ImageProcessor):
                     img_name = img.pop('name')
                     if 'caption' in img:
                         captions[img_name] = img.pop('caption')
+                    else:
+                        captions[img_name] = ""
 
                     if 'order' in img:
                         order.insert(img.pop('order'), img_name)
```

**Comment by Kwpolska** [comment]
I can’t reproduce with the demo gallery and the following `metadata.yml` file:

```yml
---
name: tesla_tower1_lg.jpg
caption: Wardenclyffe Tower
built_in: 1904
order: 2
---
name: tesla4_lg.jpg
order: 0
---
name: tesla_conducts_lg.jpg
caption: Nikola Tesla conducts electricity
order: 1
---
name: tesla_lightning1_lg.jpg
---
```

Please provide a way to reproduce (sample gallery, any config changes, etc.). Also, note that the code [explicitly handles captions not existing](https://github.com/getnikola/nikola/blob/9d3be97512480395b11db7fb3d6a57160fe63b00/nikola/plugins/task/galleries.py#L247).

**Comment by Kwpolska** [comment]
Reproduced this and #3077 with:

```yml
---
name: tesla_lightning1_lg.jpg
order:
---
```

Fix upcoming (in #3079).
